### ISSUE TITLE
Option to handle notification display missing

### ISSUE THREAD

**Issue by natangr** [one-signal/OneSignal-Android-SDK#20]
It'd be awesome to be able to manually handle the notification display on the app side. Maybe you could implement something like the touch event handled pattern, where we return true and it means that the notification has already been displayed and the library doesn't need to display it again.

**Comment by jkasten2** [comment]
You can use our [Background Data](https://documentation.onesignal.com/docs/android-notification-customizations#background-data-silent-notifications) feature to do this. Make sure to omit the 'contents' parameter when creating the notification to keep the SDK from displaying the notification.

The touch event handled pattern won't work in this case since most of the time that app wouldn't be alive when the GCM payload comes in. We are considering firing an `Intent` to a custom `BroadcastReceiver` or a `Service` for this with options to use get Android notification instance where some settings to be overridden before displaying the notification or omitting the notification all together.

**Comment by jkasten2** [comment]
Closing issue to merge the discussion with the #32 pull request.
