### ISSUE TITLE
Add callback to sendTags method

### ISSUE THREAD

**Issue by AkshayChordiya** [one-signal/OneSignal-Android-SDK#28]
Hey,

I'm using `sendTags` method to send tags to OneSignal but I want my app to move ahead once those tags are saved on OneSignal. Moreover the REST API implementation of sending tags provide a `response`.
I'm hoping to see a callback method for the `sendTags` method, something to similar to `sendTags` method callback function in **Web Push**

**Comment by jkasten2** [comment]
Thanks for the suggestion, we have opted to not to bring this callback to this SDK due to how these SDKs handle them differently.

The Android SDK does retries on setting the values for you incase of network issues as well as also saving the tags offline if there is no connection at all. Let us know if you see any issues with this and we can look into it.

Thanks.

**Comment by AkshayChordiya** [comment]
No problem. Thank you for the complete detail, it helped me.

Regards,
Akshay Chordiya
