### ISSUE TITLE
ClassCastException in OneSignal.init

### ISSUE THREAD

**Issue by ayltai** [one-signal/OneSignal-Android-SDK#47]
The init method ([OneSignal.java:196](https://github.com/one-signal/OneSignal-Android-SDK/blame/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L196)) tries to get Google project number as a `String` but it is actually an `int`, causing `ClassCastException`.

**Comment by jkasten2** [comment]
If your are manually setting `onesignal_google_project_number` in your `AndroidManifest.xml` make sure it starts with `str:` noted in [step 2.5](https://documentation.onesignal.com/docs/installing-the-onesignal-android-sdk#2-androidmanifestxml) of the OneSignal Eclipse setup documenation.

With gradle or Android Studio builds use the project number normal in `onesignal_google_project_number` in `manifestPlaceholders` per [step 1.2](https://documentation.onesignal.com/docs/android-studio-sdk-installation#1-gradle-setup) of the OneSignal Android Studio documentation. This is because the SDK's `AndroidManifest.xml` in the .aar file already includes this at [line 9](https://github.com/one-signal/OneSignal-Android-SDK/blob/2.3.0/OneSignalSDK/onesignal/src/release/AndroidManifest.xml#L9).

**Comment by ayltai** [comment]
Thanks mate
