### ISSUE TITLE
Potentially dangerous cast inside Onesignal.Log method

### ISSUE THREAD

**Issue by daisy1754** [one-signal/OneSignal-Android-SDK#5]
https://github.com/one-signal/OneSignal-Android-SDK/blob/b05676b9f4844bac4658bab5021ed0b94dd997f1/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L378

Since context here is Context type, `(Activity)context` can raise RuntimeException if caller passes non-Activity context as argument. OneSignal.Log method is public, so anyone can call it.

I believe right approach here is implement own runOnUiThread method, rather than relying on Activity's method. Following is part of platform code, and as you can see runOnUiThread method can be implemented with a few lines of code.

```
   public final void runOnUiThread(Runnable action) {
        if (Thread.currentThread() != mUiThread) {
            mHandler.post(action);
        } else {
            action.run();
        }
    }
```

Another separate but related issue is that, OneSignal.init method requires `Activity` as argument. I feel like this should be `Context` as you don't really need `Activity` here especially after you fix this bug.

**Comment by jkasten2** [comment]
Hello,

Thanks for reporting this, our `OneSignal.Log` methods were not designed to be called by the app developer but they were left open originally due to some namespace differences at one point. I have locked them down to package-private(no modifier) and private.

Thanks for the suggestion on the runOnUiThread thread. However an Activity is the only Context type that can display a dialog. I have changed the parameter to be Activity for consistency and to enforce compile time safety.

The above changes were made in commit c0bf59d6d0ce6f4290cd589d08af1eeef1f1826b.


On my roadmap I plan to rewrite how our SDK use Contexts, instead of requiring an Activity in init any context will be acceptable. I plan to use `registerActivityLifecycleCallbacks` to get the current Activity instead of hanging on to the first Activity through the lifetime of the application.

Thanks.
